language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn deploy
deploy:
  provider: pages
  github_token: 75fda100758cceb27f95c22a2becab8905dd7f2b
  local_dir: build
  on:
    branch: gh_pages
