language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - echo -e "machine github.com\n  login thang40\n  password $my_github_password"
script:
  - yarn deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_key
  local_dir: build
  on:
    branch: gh_pages
