language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_key
  local_dir: build
  on:
    branch: gh_pages
